apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  terminationGracePeriodSeconds: 40
  restartPolicy: Never
  containers:
    - name: c01
      image: ubuntu
      command:
        - sleep 
        - "5"