apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo "Calling Backend..."
                wget -qO- $BACKEND_URL
                echo ""
                echo "---"
                sleep 10
              done
          env:
            - name: BACKEND_URL
              value: "http://backend-svc.BE"
