apiVersion: v1 
kind: Pod
metadata: 
  name: pod-name #requiredResources
  labels: # filtering 
      k: v
  annotations: # extra info 
      k: v
spec: 
  containers: 
    - name: c00
      image: ubuntu
      command: 
        - /bin/bash 
        - -c 
        - |
                    while true; do
                        echo "Hello pod 2 "
                        sleep 10;
                    done

