apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod-static-name
    generateName: nginx-pod-dynamic # use create not apply
    namespace: metadata-ns
    annotations:
        description: "My 1st pod ever"
        mycompany.com/owner: "john-doe"
        project-name/created-by: "dev-team"
        example.com/environment: "production"
spec:
    containers:
        - name: nginx-c1
          image: nginx:stable-alpine3.21-perl
          ports:
              - containerPort: 80
