apiVersion: v1
kind: Pod
metadata:
    name: label-demo
    namespace: default
    annotations:
        description: "labels & selectors"
    labels:
        env: learning
        app: pod-demo
        version: v1
        tier: backend
        type: microservice                  
        component: core
        lifecycle: development
        status: active
        createdBy: codebuffdev
spec:
    containers:
        - name: nginx-c1
          image: nginx:stable-alpine3.21-perl
          ports:
              - containerPort: 80
