apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
    - image: nginx
      name: nginx-container
      ports:
        - containerPort: 80
    - image: busybox
      name: busybox-container
      command:
        - "sh"
        - "-c"
        - "sleep 3600"
